if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

set -g default-command /usr/bin/fish

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g @rose_pine_variant 'main'
set -g @rose_pine_host 'on'
set -g @rose_pine_disable_active_window_menu 'on'

# number windows from 1 not 0
set -g base-index 1

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# quickly jump between windows
bind -n C-l next-window
bind -n C-h previous-window

bind-key Tab choose-session

# use vim-like keys for splits and windows
bind-key v split-window -h
bind-key s split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# load config when tmux is open
bind r source-file ~/.config/tmux/tmux.conf

# enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# initialize plugin manager (keep at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
