set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-overrides ",*:Tc"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

set -g base-index 1
set -g mouse on
set -g set-clipboard on
setw -g mode-keys vi

set -g status-position top
set-window-option -g status-left " #S "

# from tmux-sensible
set -g escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g focus-events on
setw -g aggressive-resize on

bind tab list-sessions
bind r source-file ~/.config/tmux/tmux.conf

bind-key -n M-h previous-window
bind-key -n C-PgUp previous-window
bind-key -n M-l next-window
bind-key -n C-PgDn next-window

bind-key v split-window -h
bind-key s split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
