# --- Prompt format -------------------------------------------------------------
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

# --- SSH indicator -------------------------------------------------------------
[hostname]
ssh_only = true
format = "[$ssh_symbol$hostname]($style) in "
ssh_symbol = "⬡ "
style = "bold red"
trim_at = "."
disabled = false

[username]
show_always = false
format = "[$user]($style)@"
style_user = "bold red"
style_root = "bold red"

# --- Directory ----------------------------------------------------------------
[directory]
style = "bold cyan"
truncation_length = 4

# --- Git ----------------------------------------------------------------------
[git_branch]
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold yellow"

# --- Misc ---------------------------------------------------------------------
[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
